

run_name: mlp

output_dir: checkpoints/forecast/mlp
overwrite_output_dir: true

wandb_project_name: "crypto-forecast-m"
# === Données ===
data_path: ../data/futures/dataset/
symbols: "BTCUSDT,ETHUSDT,LTCUSDT,XRPUSDT,BCHUSDT,EOSUSDT,BNBUSDT,ADAUSDT,DOTUSDT,LINKUSDT,XLMUSDT"
tgt_symbol: "BTCUSDT"
start_date: "2020-01-01"

# === Modèle ===

src_length: 1
tgt_length: 1
seg_length: 60
type: mlp
input_features: ["open", "high", "low", "close", "volume", "taker_buy_volume", "count"]
hidden_dim: 256
output_dim: 4
num_layers: 6
dropout: 0.2
conv_kernel: 5
pool_kernel: 1
loss_function: 
  type: rmspe
  epsilon: 1.e-6
  use_close: true

# === Entraînement ===
do_eval: true
do_train: true
do_predict: true
per_device_train_batch_size: 2048
per_device_eval_batch_size: 4096
# total_batch_size: 64
# gradient_accumulation_steps: 16

max_steps: 10000
save_steps: 1000
eval_delay: 500
eval_steps: 500
eval_strategy: steps
prediction_loss_only: false
load_best_model_at_end: true
metric_for_best_model: loss
greater_is_better: false
disable_tqdm: false

ddp_find_unused_parameters: false
logging_steps: 100
save_total_limit: 3
report_to: ["wandb"]


dataloader_num_workers: 7
dataloader_drop_last: false
dataloader_pin_memory : true


learning_rate: 2.e-4
lr_scheduler_type: cosine
warmup_steps: 500
# max_grad_norm: 2.0
weight_decay: 0.01


bf16: false
fp16: true

accelerator_config:
  split_batches: false
  dispatch_batches: false
  even_batches: true
  use_seedable_sampler: true
  non_blocking: false
