seed: 42

logger:
  save_dir: logs
  name: lstm-baseline-s
  project: cerebro
  entity: null  # your wandb username/team (optional, uses default if null)
  tags:  # optional tags for organization
    - lstm
    - baseline
  notes: "LSTM baseline experiment with 64 hidden dim"  # optional experiment description

model_type: lstm

data:
  data_path: data/futures/dataset/
  src_length: 96
  tgt_length: 4
  seg_length: 15
  batch_size: 512
  num_workers: 0

model:
  type: lstm
  input_dim: 4
  hidden_dim: 128
  output_dim: 3
  seg_length: 60
  num_layers: 1
  lr: 1.e-3

trainer:
  max_epochs: 20
  eval_every_n_steps: 500 
